name: gatekeeper

services:
  db:
    image: postgres:16-alpine
    container_name: gatekeeper_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 3s      
      timeout: 3s
      retries: 10
      start_period: 2s

  migration:
    image: flyway/flyway:10-alpine
    container_name: gatekeeper_migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - FLYWAY_USER=${DB_USER}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
      - FLYWAY_SCHEMAS=gatekeeper
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    volumes:
      - ./migrations:/flyway/sql
    command: -connectRetries=10 migrate

volumes:
  postgres_data: